/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: yc                                                    *
* Dimensions:  61 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmyc;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsyc[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palyc = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acyc[] = {
  XXXXX___, ________, ________, ________, ________, ________, ________, _XXXX___,
  XXXXX___, ________, ________, ________, ________, ________, ________, __XXX___,
  XXXX____, ________, ________, ________, ________, ________, ________, __XXX___,
  XXX_____, ________, ________, ________, ________, ________, ________, ___XX___,
  XXX_____, ________, ________, ________, ________, ________, ________, ___XX___,
  XX______, ________, ________, ________, ________, ________, ________, ____X___,
  XX______, ________, ________, ________, ________, ________, ________, ____X___,
  XX______, ________, ________, ________, ________, ________, ________, ________,
  X_______, ________, ________, ________, ________, ________, ________, ________,
  X_______, ________, ________, ________, ________, ________, ________, ________,
  X_______, ________, ________, _____XXX, XXXXXXXX, X_______, ________, ________,
  ________, ________, ________, ___XXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, ________, _XXXXXXX, XXXXXXXX, XX______, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXX_____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  X_______, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  X_______, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  XX______, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  XX______, ___XXXXX, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXX____, _XXXXX__, ____X___,
  XXX_____, __XXXXX_, ______XX, XXXXXXXX, XXXXXXXX, ________, __XXXXX_, ____X___,
  XXX_____, __XXXX__, ________, __XXXXXX, XXXXXX__, ___XXXXX, X_XXXXX_, ____X___,
  XXXX____, __XXX___, XXXXXX__, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____X___,
  XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ____X___,
  XXXXX___, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___XX___,
  XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX___XXX, XXXXXXX_, __XXX___,
  XXXXX___, _XXXXXXX, XX______, XXXXXXXX, XXXXXXXX, ________, XXXXXXX_, __XXX___,
  XXXX_X__, _XXXXXX_, ___X____, __XXXXXX, XXXXXXX_, X___XX__, _XXXXXXX, __XXX___,
  XXX__XX_, _XXXXX__, ___XX__X, X__XXXXX, XXXXXXX_, XX__XXX_, __XXXXXX, _XXXX___,
  XXX__XX_, _XXXXX__, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXX_XXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXX_, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXX___, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXX___,
  XXXX___X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXX___,
  XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXX___,
  XXXXXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, _X____XX, XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ___XXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXX__X, XXXXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXX___, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, XX___XXX, XXXXX___,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXX___,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_____XX, XXXXX___,
  XXXXXXXX, XXX_____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, XXXXX___,
  XXXXXXXX, XXX_____, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, XXXXX___,
  XXXXXXXX, XX______, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X______X, XXXXX___,
  XXXXXXXX, X_______, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, XXXXX___,
  XXXXXXXX, ________, XXXXXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, _XXXX___,
  XXXXXXX_, ________, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, ________, ___XX___
};

GUI_CONST_STORAGE GUI_BITMAP bmyc = {
  61, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acyc,  // Pointer to picture data (indices)
  &_Palyc   // Pointer to palette
};

/*************************** End of file ****************************/
